### ISSUE TITLE
Get CI working on all architectures

### ISSUE THREAD

**Issue by pksunkara** [pksunkara/pgx_ulid#1]

**Comment by justinrubek** [comment]
This is slightly related, so I thought I'd mention here. I can make it a separate issue if you'd like, or drop the topic.

I packaged `pgx_ulid` with nix so that I could use it in nix contexts. I loosely followed [pgx's template](https://github.com/tcdi/pgx/tree/master/nix/templates/default) but I had to take some liberties to get it to work (this is something that could probably get worked on in their project to be a bit easier).

What I've written needs a little bit of work to handle different postgres versions, but it could help accomplish this. It is still in need of cleanup as I had to work through a few problems before it worked properly. I've got it up on my fork here https://github.com/justinrubek/pgx_ulid.

If there isn't much interest I'll probably leave it how it is for a while. It seems to work fine for my use case as is

**Comment by pksunkara** [comment]
I will leave the nix release to you. I don't have enough experience with it.
