### ISSUE TITLE
Postgres + ulid [XX000] ERROR: Can't give out exclusive, lock is in an empty state

### ISSUE THREAD

**Issue by wasdee** [pksunkara/pgx_ulid#12]
from https://dba.stackexchange.com/questions/329047/postgres-ulid-xx000-error-cant-give-out-exclusive-lock-is-in-an-empty-sta/329048#329048

There is an novel error when trying insert row.

The database is setup with https://github.com/pksunkara/pgx_ulid.
And it is using a function `gen_monotonic_ulid()` as a default.

I followed the readme guide and added the `shared_preload_libraries = 'ulid'`.
With or without this, the error still persisted.

## Setup Details
there is also postgis installed.
```
FROM postgis/postgis:${PG_MAJOR}-3.3
...
COPY postgres.conf /etc/postgresql/postgresql.conf
CMD ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
```

do you have any advice for my case?

**Comment by pksunkara** [comment]
@liljaylj Do you have any idea what's happening here?

I don't think we have a test for this function, right?

**Comment by workingjubilee** [comment]
The source of this error is https://github.com/pgcentralfoundation/pgrx/blob/159295238f7513da2e4c7075b004cf0b5a60d30b/pgrx/src/lwlock.rs#L74-L77

Which is called by https://github.com/pksunkara/pgx_ulid/blob/eb8e9cff70fa70cbb540f40351750e3cd01cd7fa/src/lib.rs#L73-L75

There have been recent reports of various issues with the shared memory infrastructure in pgrx, unfortunately. This at least simply yields a fairly predictable error instead of UB, I suppose.

**Comment by gjtorikian** [comment]
I encountered this issue as well. But what worked for me was 

```
ALTER SYSTEM SET shared_preload_libraries = ulid;
```

rather than changing `postgresql.conf`.

**Comment by pksunkara** [comment]
I added docs. Please let me know if none of the two above steps works and I will re-open the issue.
