### ISSUE TITLE
How can I use it on MacOS Postgres?

### ISSUE THREAD

**Issue by israelins85** [pksunkara/pgx_ulid#26]
I tried to put the files on /opt/homebrew/share/postgresql@14/extension/ulid.control
but no success.

**Comment by pksunkara** [comment]
What files did you put? Please describe the issue with full details.

**Comment by israelins85** [comment]
Sorry... I have to use cargo pgrx install... But I use the normal Postgres from Homebrew. This will work?

**Comment by pksunkara** [comment]
Hello,

We appreciate your enthusiasm to contribute to this open-source project and to help make it better. Unfortunately, there's not enough information in your bug report for me to understand what this issue is about. Can you please add clear-cut steps on how to reproduce this error?

To make effective usage of the maintainers' time, we will be closing this issue until further information as requested is provided.

Thanks
